# Generated by Django 5.2.3 on 2025-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(default='M', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=2),
        ),
    ]
