# Generated by Django 5.2.3 on 2025-08-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='selected_size',
        ),
    ]
